server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: 200628
  data:
    redis:
      host: localhost
      port: 6379
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xiaosa.securityhello.domain
  configuration:
    map-underscore-to-camel-case: true
